"""renamed hike distance field

Revision ID: 1cc193cb0099
Revises: 820987ccf898
Create Date: 2023-01-26 15:17:08.234393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc193cb0099'
down_revision = '820987ccf898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.drop_column('d')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('d', sa.FLOAT(), nullable=True))
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
