"""empty message

Revision ID: 8463f4b94388
Revises: be28d2b9972f
Create Date: 2023-01-20 16:38:23.451066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8463f4b94388'
down_revision = 'be28d2b9972f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('displayname', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(length=150), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('displayname'),
    sa.UniqueConstraint('fullname')
    )
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trail_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_index('ix_route_timestamp')

    op.drop_table('route')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('displayname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=150), nullable=False),
    sa.Column('length', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('displayname'),
    sa.UniqueConstraint('fullname')
    )
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_index('ix_route_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trail_timestamp'))

    op.drop_table('trail')
    # ### end Alembic commands ###
