"""removed filename

Revision ID: b2fa9f4cb2a7
Revises: 9a20444868eb
Create Date: 2023-01-23 14:09:03.641691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fa9f4cb2a7'
down_revision = '9a20444868eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=150), nullable=True))

    # ### end Alembic commands ###
